home/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "home"

urlpatterns = [
    path('', views.HomeView.as_view(), name = "home"),
    path('category/<slug>/', views.CategoryView.as_view(), name = "category"),
    path('add-to-cart/', views.add_to_cart, name = "add-to-cart"),
    path('order-summary/', views.OrderSummaryView.as_view(), name = "summary"),
    path('update-cart/', views.update_cart, name = "update_cart")
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)

mana_store/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('home.urls')),
    
]

home/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse

# Create your models here.


Quantity_Choices = (
    ("k", "KG"),
    ("l", "Ltrs"),
    ("d", "Dozens"),
    ("u", "Units")
)

class Category(models.Model):
    category = models.CharField(max_length=30)
    img = models.ImageField(upload_to='pics')
    slug = models.SlugField()
    
    def __str__(self):
        return self.category
    
    def get_absolute_url(self):
        return reverse("home:category", kwargs={
            'slug': self.slug
        })

class SubCategory(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    sub_category = models.CharField(max_length = 100)
    def __str__(self):
        return self.sub_category
        
class Item(models.Model):
    title = models.CharField(max_length = 100)
    sub_category = models.ForeignKey(SubCategory, on_delete=models.CASCADE)
    img = models.ImageField(upload_to='pics')
    description = models.TextField()
    measured_by = models.CharField(choices=Quantity_Choices, max_length=1)
    slug = models.SlugField()
    
    def __str__(self):
        return self.title

class Price(models.Model):
    item = models.OneToOneField(Item, on_delete=models.CASCADE)
    kkd_rural_p = models.FloatField(blank=True, null=True)
    kkd_urban_p = models.FloatField(blank=True, null=True)
    
    kkd_rural_dp = models.FloatField(blank=True, null=True)
    kkd_urban_dp = models.FloatField(blank=True, null=True)
    
    def __str__(self):
        return self.item.title
    
    
    
class OrderItem(models.Model):
    item = models.ForeignKey(Price, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    ordered = models.BooleanField(default = False)
    quantity = models.FloatField(default = 1)
    price = models.FloatField(blank=True, null=True)
    discounted_price = models.FloatField(blank=True, null=True)
    def __str__(self):
        return self.item.item.title
    def get_total_discount_item_price(self):
        return self.discounted_price*self.quantity
    def get_amount_saved(self):
        return (self.price- self.discounted_price)*self.quantity
    def get_total_item_price(self):
        return self.price*self.quantity
    
    
class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add = True)
    order_date = models.DateTimeField(blank=True, null=True)
    ordered = models.BooleanField(default = False)
    total_amount = models.FloatField(blank=True, null=True)
    amount_saved = models.FloatField(blank=True, null=True)
    def __str__(self):
        return self.user.name
    def get_total(self):
        return self.total_amount
    def get_saved(self):
        return self.amount_saved
    

home/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from home.models import Item, Category, Price, SubCategory, OrderItem, Order
from account.models import Account
from django.http import HttpResponse 
from django.views.generic import ListView, DetailView, View
import json
from django.utils.text import slugify
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from django.shortcuts import redirect
from django.contrib.auth.models import AnonymousUser

# Create your views here.
class HomeView(ListView):
    model = Category
    template_name = "home.html"
        
class CategoryView(DetailView):
    model = Category
    template_name = "category.html"
    def get_context_data(self, **kwargs):
        category = self.request.GET.get('c', None)
        # Call the base implementation first to get the context
        context = super(CategoryView, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        area = "kkd_rural"
        PriceFiltered = Price.objects.filter(item__sub_category__category__category__in = [context['object']])
        if category is None:
            context['Area'] = PriceFiltered.only("item", area+"_p", area+"_dp")
        else:
            context['Area'] = PriceFiltered.filter(item__sub_category__sub_category__in =[category]).only("item", area+"_p", area+"_dp")
            context['curr'] = category
        context['sub_c'] = SubCategory.objects.filter(category=context['object'])
        slugs = {}
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            for item in order.items.all():
                slugs[getattr(item.item.item, "slug")] = getattr(item, "quantity")
            context['slugs'] = slugs
        except ObjectDoesNotExist:
            pass
        except TypeError:
            pass
        return context

class OrderSummaryView(LoginRequiredMixin, View):
    login_url = '/account/login/'
    redirect_field_name = 'next'
    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            area = "kkd_rural"
            total, saved = 0, 0
            
            for item in order.items.all():
                item.price = getattr(item.item, area+"_p")
                item.discounted_price = getattr(item.item, area+"_dp")
                item.save()
                if(item.discounted_price):
                    total+=item.get_total_discount_item_price()
                    saved+=item.get_amount_saved()
                else:
                    total+=item.get_total_item_price()
            order.total_amount = total
            order.amount_saved = saved
            context = {
                'object': order
            }
            return render(self.request, 'order_summary.html', context)
        except ObjectDoesNotExist:
            messages.warning(self.request, "You do not have an active order")
            return redirect("/")
        
def update_cart(request):
    return HttpResponse("<h1>Working<h1>")

#Ajax Functions
def add_to_cart(request):
    if not request.user.is_authenticated:
        messages.warning(request, "Please Login First")
        next_url = "/account/login/?next="+request.GET.get('next', None)
        return HttpResponse(json.dumps({"Status": False, "next": next_url}), content_type="application/json")
    slug = request.GET.get('slug', None)
    quantity = request.GET.get('quantity', None)
    if slug is None:
        return HttpResponse(json.dumps({"Status": False}), content_type="application/json")
    item = get_object_or_404(Item, slug=slug)
    area = get_object_or_404(Price, item=item)
    order_item, created = OrderItem.objects.get_or_create(item = area, user = request.user, ordered = False)
    order_item.quantity = int(quantity)
    order_item.save()
    order_qs = Order.objects.filter(user = request.user, ordered = False)
    if(quantity == '0'):
        order_item.delete()
        count = order_qs[0].items.count()
        if(order_qs.exists() and order_qs[0].items.count() == 0):
            order_qs[0].delete()
        return HttpResponse(json.dumps({"Status": False, "count": count}), content_type="application/json")
    
    if(order_qs.exists()):
        if(not order_qs[0].items.filter(item__item__slug = slugify(slug)).exists()):
            order_qs[0].items.add(order_item)
    else:
        order = Order.objects.create(user = request.user)
        order.items.add(order_item)
    return HttpResponse(json.dumps({"Status": True, "count": order_qs[0].items.count()}), content_type="application/json")

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  
  <link rel='icon' href = "{% static 'Images/favicon.ico' %}" type='image/x-icon'/>
  <title>{% block title %}{% endblock %}</title>
  {% block extra_head %}
  {% endblock %}
  <!-- Font Awesome -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
<!-- Google Fonts -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
<!-- Bootstrap core CSS -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
<!-- Material Design Bootstrap -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.0/css/mdb.min.css" rel="stylesheet">
  <link href="{% static 'CSS/booths.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>

{% include "navbar.html" %}

<body>

    <div class="mt-5 pt-4">
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
    {% endif %}
    </div>

    {% block body %}
    {% endblock body %}

    {% block extra_body %}
    {% endblock %}

    {% include "scripts.html" %}

    {% block extra_scripts %}
    {% endblock extra_scripts %}
</body>
</html>

templates/category.html
{% extends "base.html" %}
{% load price_tags %}
{% load static %}
{% block title %}{{object}}{% endblock %}
{% block body %}
  <main>
    <div class="container">
    <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            {% if curr %}
            <li class="nav-item">
            {% else %}
            <li class="nav-item active">
            {% endif %}
              <a class="nav-link" href="?">All
                <span class="sr-only">(current)</span>
              </a>
            </li>
              {% for category in sub_c %}
            {% if curr == category.sub_category %}
            <li class="nav-item active">
            {% else %}
            <li class="nav-item">
            {% endif %}
              <a class="nav-link" href="?c={{category}}">{{category}}</a>
            </li>
            {% endfor %}

          </ul>
          <!-- Links -->

          <form class="form-inline">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name="search" id="search">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->
      
      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <div class="row wow fadeIn">

          {% for area in Area|dictsort:'item.sub_category.sub_category' %}
            
          <div class="col-lg-3 col-md-6 mb-4 block">
            <div class="card">

              <div class="view overlay">
                
                <img src="{{ area.item.img.url }}" class="card-img-top">
                
              </div>

              <div class="card-body text-center">
                <h5>
                  <strong>
                    <a href="#" class="dark-grey-text">{{ area.item }}
                    </a>
                  </strong>
                </h5>
                <h6>
                  <strong class="font-weight-bold blue-text">Rs.
                  {% if area|col:"1" %}
                  {{ area|col:"1" }}
                  {% else %}
                  {{ area|col:"0" }}
                  {% endif %}
                  </strong><span>/ {{area.item.get_measured_by_display}}</span>
                </h6>
                {% if area.item.slug|inside:slugs %}
                    <div class="number-input">
                    <button onclick="this.parentNode.querySelector('input[type=number]').stepDown()" class="btn-sm"></button>
                    <input class="quantity form-control" min=0 name="quantity" value={{slugs|get:area.item.slug}} type="number" >
                    <button onclick="this.parentNode.querySelector('input[type=number]').stepUp()" class="btn-sm plus"></button>
                    </div>
                    <button class="btn btn-danger add">
                      Update Cart
                    </button>
                {% else %}
                    <div class="number-input">
                    <button onclick="this.parentNode.querySelector('input[type=number]').stepDown()" class="btn-sm"></button>
                    <input class="quantity form-control" min=0 name="quantity" value=0 type="number" >
                    <button onclick="this.parentNode.querySelector('input[type=number]').stepUp()" class="btn-sm plus"></button>
                    </div>
                    <button class="btn btn-primary add">
                      Add to cart
                    </button>
                
                {% endif %}
                <input value="{{area.item.slug}}" hidden/>
              
                </div>
            </div>

          </div>
            {% endfor %}
        </div>

      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->

      {% if is_paginated %}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}

          <li class="page-item active">
            <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
              <span class="sr-only">(current)</span>
            </a>
          </li>

          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      {% endif %}

    </div>
  </main>
{% endblock body %}
{% block extra_scripts %}
<script type="text/javascript" src="{% static 'javaScripts/searchScript.js' %}"></script>
{% endblock extra_scripts %}

templates/changePasswd.html
{% extends "Base.html" %}

{% block title %}Change Password{% endblock %}

{% block navbar %}
      <ul class="nav navbar-nav">
        <li><a href="/">Home</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
       {% if user.is_authenticated %}
          <li><div class="dropdown">
              <button class="dropbtn">{{user.name}}</button>
              <div class="dropdown-content">
                <a href="/account/profileView">View Profile</a>
                <a href="/account/profileEdit">Edit Profile</a>
                <a href="/account/changePasswd">Change Password</a>
              </div>
            </div></li>
        <li><a href="/account/logout">Logout</a></li>
       {% else %}
        <li><a href="/account/register">Register</a></li>
        <li><a href="/account/login">Login</a></li>
       {% endif %}
      </ul>
{% endblock %}

{% block body %}
<main>
    <div class="container">
      <section class="mb-4">
        <div class="row wow fadeIn">
          <div class='col-6 offset-3'>
  
  <form action='/account/changePasswd/' method='post' onSubmit="return beforeSubmit()" class="form-horizontal" enctype="multipart/form-data">
   {% csrf_token %}
   <span><h3>Change Password</h3></span>
    
        {% for message in messages %}
    <label style="color:#ed3c2f;">{{message}}</label><br>
      {% endfor %}
      
    <div class="form-group">
        <label class="col-sm-2 control-label" align="right">Current Password: </label>
      <div class="col-sm-12">
        <input class="form-control" id="oldPasswd" type="password" name="oldPasswd" placeholder="Current Password" required>
      </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label" align="right">Password: </label>
      <div class="col-sm-12">
        <input class="form-control" id="password" type="password" name="password" placeholder="new Password" required>
      </div>
    </div>
      <div class="form-group">
        <label class="col-sm-2 control-label" align="right">Confirm Password: </label>
      <div class="col-sm-12">
        <input class="form-control" id="repassword" type="password" name="repassword" placeholder="Confirm Password" required>
      </div>
    </div>
    <button id="submit" type="submit" class="btn btn-primary">
     Update Password
    </button>
      
  </form>  
</div>
</div>
      </section>
    </div>
  </main>
{% load static %}
<script type="text/javascript" src="{% static 'javaScripts/preValidation.js' %}"></script>
{% endblock %}

templates/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block body %}
<div class="mt-5 pt-4"></div>
  <main>
    <div class="container">

      
      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <div class="row wow fadeIn">

          {% for item in object_list %}
          <div class="col-lg-3 col-md-6 mb-4">

            <div class="card">

              <div class="view overlay">
                
                <img src="{{ item.img.url }}" class="card-img-top">
                <a href="{{ item.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>

              <div class="card-body text-center">
                <h5>
                  <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item }}
                    </a>
                  </strong>
                </h5>

                
              </div>

            </div>

          </div>
          {% endfor %}
        </div>

      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->

      {% if is_paginated %}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}

          <li class="page-item active">
            <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
              <span class="sr-only">(current)</span>
            </a>
          </li>

          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      {% endif %}

    </div>
  </main>

{% endblock body %}

templates/login.html
{% extends "Base.html" %}

{% block title %}Login{% endblock %}

{% block body %}
    <main>
    <div class="container">
      <section class="mb-4">
        <div class="row wow fadeIn">
          <div class='col-6 offset-3'>
          <h1>Sign In</h1>

          <p>If you have not created an account yet, then please
          <a href="{% url 'register' %}">sign up</a> first.</p>
  <form action='/account/login/' method='post' class="form-horizontal">
  {% csrf_token %}
   <span><h3>Account Login</h3></span>
   <span><h5 id="logOut"></h5></span>
    <div class="form-group">
      <label class="col-sm-2 control-label" align="right"> Phone: </label>
      <div class="col-sm-12">
        <input class="form-control" id="phone" type="tel" name="phone" placeholder="987654210" pattern="[0-9]{10}" required>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label" align="right"> Password: </label>
      <div class="col-sm-12">
        <input class="form-control" id="password" type="password" name="password" placeholder="Password" required>
      </div>
    </div>
      {% if next %}
      <input type="hidden" name="next" value="{{next}}" />
      {% endif %}
    <div class="form-group">
    <button type="submit" class="btn btn-primary">
     Sign in
    </button>
        </div>
  </form>
              </div>
        </div>
      </section>
    </div>
  </main>
{% endblock %}

templates/navbar.html
{% load price_tags %}
<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="/">
        <strong class="blue-text">MANA STORE</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          {% comment %} <li class="nav-item active">
            <a class="nav-link waves-effect" href="/">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="/checkout">
            Checkout</a>
          </li> {% endcomment %}
        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a href="/order-summary" class="nav-link waves-effect">
              <span class="badge red z-depth-1 mr-1" id="cart_count"> {{ request.user|cart_count }} </span>
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>
            <li><div class="dropdown">
              <a class="dropbtn clearfix d-none d-sm-inline-block">{{request.user.name}}</a>
              <div class="dropdown-content">
                <a href="/account/profileView">View Profile</a>
                <a href="/account/profileEdit">Edit Profile</a>
                <a href="/account/changePasswd">Change Password</a>
              </div>
            </div></li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'logout' %}">
              <span class="clearfix d-none d-sm-inline-block"> Logout </span>
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'login' %}">
              <span class="clearfix d-none d-sm-inline-block"> Login </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'register' %}">
              <span class="clearfix d-none d-sm-inline-block"> Signup </span>
            </a>
          </li>
          {% endif %}
        </ul>
      </div>

    </div>
  </nav>

templates/order_summary.html
{% extends "base.html" %}
{% load price_tags %}

{% block body %}
  <main>
    <div class="container">

    <div class="table-responsive text-nowrap">
    <h2>Order Summary</h2>
    <table class="table">
        <thead>
        <tr>
            <th class="text-center align-middle" scope="col">Item title</th>
            <th class="text-center align-middle" scope="col">Price</th>
            <th class="text-center align-middle" scope="col">Quantity</th>
            <th class="text-center align-middle" scope="col">Total Item Price</th>
        </tr>
        </thead>
        <tbody>
        {% for order_item in object.items.all %}
        <tr>
            <td class="text-center align-middle">{{ order_item.item.item.title }}</td>
            <td class="text-center align-middle">{{ order_item.price }}/{{order_item.item.item.get_measured_by_display}}</td>
            <td class="text-center align-middle"><a onclick="this.parentNode.querySelector('input[type=number]').stepDown()"><i class="fas fa-minus mr-2"></i></a>
                <input class="quantity" min=0 name="quantity" value="{{ order_item.quantity }}"  type="number" style="width: 3em">
                <a onclick="this.parentNode.querySelector('input[type=number]').stepUp()"><i class="fas fa-plus ml-2"></i></a>
                <button class="btn btn-sm "  disabled>update</button>
            </td>
            <td class="text-center align-middle">
            {% if order_item.discounted_price %}
                ₹{{ order_item.get_total_discount_item_price }}
                <span class="badge badge-primary">Saving ₹{{ order_item.get_amount_saved }}</span>
            {% else %}
                ₹{{ order_item.get_total_item_price }}
            {% endif %}
            <a style='color: red;' href="#">
                <i class="fas fa-trash float-right"></i>
            </a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan='4'>Your cart is empty</td>
        </tr>
        <tr>
            <td colspan="4">
            <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
            </td>
        </tr>
        {% endfor %}
        {% if object.coupon %}
        <tr>
            <td colspan="3"><b>Coupon</b></td>
            <td><b>-₹{{ object.coupon.amount }}</b></td>
        </tr>
        {% endif %}
        {% if object.get_total %}
        <tr>
            <td colspan="3"><b>Order Total</b></td>
            <td><b>₹{{ object.get_total }}</b>
            {% if object.get_saved %}
            <span class="badge badge-primary">Saving ₹{{ object.get_saved }}</span>
            {% endif %}
            </td>
        </tr>
        <tr>
            <td colspan="4">
            <a class='btn btn-warning float-right ml-2' href='/checkout/'>Proceed to checkout</a>
            <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
            </td>
        </tr>
        {% endif %}
        </tbody>
    </table>

    </div>

    </div>
  </main>

{% endblock body %}

templates/profileView.html
{% extends "Base.html" %}

{% block title %}Profile Details{% endblock %}

{% block navbar %}
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Home</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
       {% if user.is_authenticated %}
          <li><div class="dropdown">
              <button class="dropbtn">{{user.name}}</button>
              <div class="dropdown-content">
                <a href="/account/profileView">View Profile</a>
                <a href="/account/profileEdit">Edit Profile</a>
                <a href="/account/changePasswd">Change Password</a>
              </div>
            </div></li>
        <li><a href="/account/logout">Logout</a></li>
       {% else %}
        <li><a href="/account/register">Register</a></li>
        <li><a href="/account/login">Login</a></li>
       {% endif %}
      </ul>
{% endblock %}

{% block body %}
<main>
    <div class="container">
      <section class="mb-4">
        <div class="row wow fadeIn">
          <div class='col-6 offset-3'>
    {% if user.is_authenticated %}
    <div class="form-group">
    <div class="col-sm-2"></div>
      <label class="col-sm-2 control-label" align="right">Name: </label>
      <div class="col-sm-4">
        <label class="col-sm-4 control-label" align="right">{{user.name}}</label>
      </div>
     </div><br><br>
    <div class="form-group">
        <div class="col-sm-2"></div>
      <label class="col-sm-2 control-label" align="right">Email: </label>
      <div class="col-sm-4">
        <label class="col-sm-4 control-label" align="right">{{user.email}}</label>
      </div>
    </div><br><br>
    <div class="form-group">
        <div class="col-sm-2"></div>
        <label class="col-sm-2 control-label" align="right">Phone: </label>
      <div class="col-sm-4">
        <label class="col-sm-4 control-label" align="right">{{user.phone}}</label>
      </div>
    </div><br><br>
    {% endif %}
</div>
        </div>
      </section>
    </div>
  </main>


{% endblock %}